
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: short_links_php
    command: sh -c "/usr/local/bin/wait-for-it mysql:3306 --timeout=30 -- php yii migrate --interactive=0 && php-fpm"
    depends_on:
      - mysql
    networks:
      - short_links_network

  nginx:
    image: nginx:alpine
    container_name: short_links_nginx
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html/web
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - short_links_network

  mysql:
    image: mysql:8.0
    container_name: short_links_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

    ports:
      - "3310:3306"
    networks:
      - short_links_network

  composer:
    image: composer:2
    container_name: short_links_composer
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - short_links_network

volumes:
  mysql_data:

networks:
  short_links_network:
    driver: bridge